/* Shared visual shell. Account services are handled by CourtApp; drafts here stay in memory. */
(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY=document.documentElement.dataset.storageKey==='sidecourt-visitor-v1'?'sidecourt-visitor-v1':'sidecourt-marketing-candidate-v1';
const names={home:'Home',drops:'DROPS',season:'Season I','get-on':'Get on the court',inside:'The Inside',white:'Your draft',work:'CleanPause',account:'Account connections',player:'M1NGA',court:'Your Court',settings:'Settings',preview:'Private work preview','not-found':'Page not found','season-join':'Prepare your Season entry','season-entry':'Your Season entry'};
const blank=()=>({version:1,saved:false,note:'',intent:'',name:'',draft:null,workspace:{},updated:''});
const str=(v,n=8000)=>typeof v==='string'?v.slice(0,n):'';
const safeURL=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const safeCover=v=>typeof v==='string'&&v.length<1500000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v)?v:'';
const sanitizeDraft=d=>d&&typeof d==='object'?{name:str(d.name,48),author:str(d.author,32),description:str(d.description,160),url:str(d.url,2048),why:str(d.why),start:str(d.start),invitation:['question','need'].includes(d.invitation)?d.invitation:'none',invitationBody:str(d.invitationBody),cardLine:str(d.cardLine,100),repository:str(d.repository,2048),reuse:str(d.reuse,1000),cover:safeCover(d.cover),files:Array.isArray(d.files)?d.files.slice(0,30).map(f=>({name:str(f?.name,200),size:Number.isFinite(f?.size)&&f.size>=0?f.size:0})):[]}:null;
let state=blank(),loadWarning='';
// Cloud mode starts with no prototype records. Draft text stays in memory until explicitly saved.
let draftCover=state.draft?.cover||'',fileMetadata=state.draft?.files||[],sessionFiles=[],coverRead=0;
let draftTimer,noteTimer,intent=state.intent,current='',dropReturn='#drops',insideReturn='#home';
const scrolls=new Map();let demoTimer,holdTimer,holdStart=0,demoActive=false;
const say=(selector,message)=>{$(selector).textContent=message};
function commit(patch,selector,success){
 const next={...state,...patch,updated:new Date().toISOString()};
 try{state=next;if(selector)say(selector,success);return true}
 catch{if(selector)say(selector,'Not saved. This browser could not store the change. Your current text is still here; export it from Settings before closing.');return false}
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function draftData(){const f=new FormData($('#work-form'));return {name:str(f.get('name'),48),author:str(f.get('author'),32),description:str(f.get('description'),160),url:str(f.get('url'),2048),why:str(f.get('why')),start:str(f.get('start')),invitation:f.get('invitation')||'none',invitationBody:str(f.get('invitationBody')),cardLine:str(f.get('cardLine'),100),repository:str(f.get('repository'),2048),reuse:str(f.get('reuse'),1000),cover:draftCover,files:fileMetadata}}
function hasDraft(d){return !!d&&(!!d.name.trim()||!!d.description.trim()||!!d.url.trim()||!!d.why.trim()||!!d.start.trim()||!!d.invitationBody.trim()||!!d.cardLine?.trim()||!!d.repository?.trim()||!!d.reuse?.trim()||!!d.cover||d.files.length>0)}
function saveDraft(){clearTimeout(draftTimer);draftTimer=null;return window.CourtApp?.saveDraft();}
function syncDraftPreview(){const d=draftData();say('#draft-preview-name',d.name||'Your work’s name');say('#draft-preview-author',d.author?`BY ${d.author}`:'Your author name');say('#draft-preview-description',d.description||'One sentence about what someone can explore.');$('#draft-preview-cover').hidden=!draftCover;$('#draft-cover-placeholder').hidden=!!draftCover;if(draftCover)$('#draft-preview-cover').src=draftCover;else $('#draft-preview-cover').removeAttribute('src');$('#remove-cover').hidden=!draftCover;$('#invitation-detail').hidden=d.invitation==='none';$('#invitation-detail').firstChild.textContent=d.invitation==='need'?'What is one specific thing someone could help with? Include useful materials and boundaries.':'What would you like someone to notice or tell you?';$$('[data-count]').forEach(n=>{const f=document.getElementById(n.dataset.count);n.textContent=`${f.value.length} / ${f.maxLength}`});window.CourtApp?.renderLiveCard(d)}
function restoreDraft(){const f=$('#work-form');f.reset();const d=state.draft;if(d){for(const [key,value] of Object.entries(d)){const input=f.elements.namedItem(key);if(!input||['cover','files'].includes(key))continue;if(key==='invitation')input.value=value;else input.value=value;}}else $('#draft-author').value=state.name;draftCover=d?.cover||'';fileMetadata=d?.files||[];syncDraftPreview();renderFiles()}
function renderFiles(){say('#files-status',fileMetadata.length?`${fileMetadata.map(f=>f.name).join(', ')}. Check upload status below; public downloads need review and your publishing choice.`:'Select files to attach to your work. Sign in to upload; completed uploads stay private until reviewed and published.')}
function renderPreview(d=draftData()){const url=safeURL(d.url);if(!hasDraft(d)){$('#full-work-preview').innerHTML='<div class="empty glass"><h2>A place for your first draft.</h2><p>Start with a name or a sentence. You can preview before filling everything in.</p><a class="button" href="#white">Start a draft →</a></div>';return}
 $('#full-work-preview').innerHTML=`<section class="work-heading"><div><p class="attribution">${esc(d.author?'BY '+d.author:'AUTHOR NAME NOT ADDED')}</p><h1>${esc(d.name||'Untitled work')}</h1><p>${esc(d.description||'Add a sentence about what someone can explore.')}</p>${url?`<a class="button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Explore this work ↗</a>`:d.url?'<p class="local-note">This link is not a valid http or https address. Edit it before sharing.</p>':''}</div>${d.cover?`<img class="work-media" src="${esc(d.cover)}" alt="Your selected cover">`:'<div class="cover-placeholder">Your work. Your point of view.</div>'}</section><div class="glass preview-details">${d.why?`<h2>Why I made it.</h2><p>${esc(d.why)}</p>`:''}${d.start?`<h2>Where to start.</h2><p>${esc(d.start)}</p>`:''}${d.invitation!=='none'?`<h2>${d.invitation==='need'?'An invitation to help.':'A question from the author.'}</h2><p>${esc(d.invitationBody||'Add the question or invitation you would like someone to see.')}</p>`:''}${d.files.length?`<h2>Files</h2><p>Names and sizes only. Files have not been uploaded or published.</p><ul class="preview-file-list">${d.files.map(f=>`<li>${esc(f.name)} · ${Math.ceil(f.size/1024)} KB${sessionFiles.some(s=>s.name===f.name&&s.size===f.size)?' · selected this session':' · select again in the editor'}</li>`).join('')}</ul>`:''}<p class="local-note">Private layout preview. Nothing on this page has been published or sent for review.</p></div>`;
}
function renderCourt(){if(window.CourtApp)return window.CourtApp.renderCourt();$('#court-content').innerHTML='<h2>Your workspace is loading.</h2><p>If this message stays here, reload the page. Your account has not changed.</p><a class="text-link" href="#drops">Explore works →</a>';}
function updateSaved(){const b=$('#save-work');b.setAttribute('aria-pressed',String(state.saved));b.textContent=state.saved?'Saved · remove':'Save for later'}
function filterWorks(params,write=false){const search=$('#drop-search'),need=$('#need-filter');let help;if(window.CourtApp)return window.CourtApp.filterWorks(params,write);
 if(params){search.value=params.get('q')||'';need.checked=params.get('needs')==='1';help=params.get('help')==='1';$$('[data-discovery]').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.discovery==='help')===help)))}else help=$('[data-discovery="help"]').getAttribute('aria-pressed')==='true';
 const query=search.value.trim().toLowerCase();const match=!need.checked&&(!query||'cleanpause m1nga keyboard trackpad screen cleaning accidental input'.includes(query));
 $('#drop-results').hidden=!match;$('#drop-empty').hidden=match;$('#help-invitation').hidden=!help;
 say('#discovery-context',help?'Questions and specific requests from authors. Start with the work and choose what you can offer.':'One founder work to explore. More works will appear here as they are published.');
 say('#empty-heading',need.checked?'No specific help requests are open.':'No drops match this search.');say('#empty-description',need.checked?'No matching author requests are available. Clear your search and filters to explore works.':'Try the work’s name, its author, or what it does.');
 say('#result-status',match?'One work shown.':'No works shown.');$('.filters summary').textContent=need.checked?'Filter · 1':'Filter';
 if(write){const p=new URLSearchParams();if(query)p.set('q',search.value);if(help)p.set('help','1');if(need.checked)p.set('needs','1');const hash='#drops'+(p.size?'?'+p:'');try{history.replaceState(null,'',hash);current=hash;dropReturn=hash}catch{}}
}
function route(force=false){const hash=location.hash||'#home';if(hash===current&&force!==true)return;if(hash.startsWith('#main-'))return;const [raw,query='']=hash.slice(1).split('?'),page=Object.hasOwn(names,raw)?raw:'not-found',previous=current.split('?')[0];if(current)scrolls.set(current,window.scrollY);if(previous==='#drops')dropReturn=current;if(page==='inside'&&previous&&previous!=='#inside')insideReturn=current;current=hash;
 $$('[data-page]').forEach(n=>n.hidden=n.dataset.page!==page);$$('.mobile-nav[open]').forEach(n=>n.open=false);$$('.nav a,.mobile-nav a').forEach(n=>{const hit=n.getAttribute('href')==='#'+page;if(hit)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current')});if($('#scene-select'))$('#scene-select').value=page;$('.skip').setAttribute('href','#main-'+page);document.title='SideCourt · '+names[page];
 if(page==='drops')filterWorks(new URLSearchParams(query));if(page==='court')renderCourt();if(page==='preview')renderPreview();if(page==='settings')$('#settings-name').value=state.name;window.CourtApp?.onRoute(page,new URLSearchParams(query));
 $$('[data-back-drops]').forEach(a=>a.setAttribute('href',dropReturn));$$('[data-return]').forEach(a=>a.setAttribute('href',insideReturn));
 if(page!=='work')exitDemo();const main=$('#main-'+page);main.focus({preventScroll:true});requestAnimationFrame(()=>{if(current!==hash)return;const p=new URLSearchParams(query);if(page==='season'&&p.get('section')==='rules'){const target=$('#season-rules');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else if(page==='preview'&&p.get('section')==='details'&&$('#preview-details')){const target=$('#preview-details');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else if(page==='work'&&(p.has('question')||p.has('compose'))){const target=p.has('question')?$('#author-question'):$('#activity-text');if(p.has('question'))target.setAttribute('tabindex','-1');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else window.scrollTo({top:scrolls.get(hash)||0,behavior:'auto'})});
}
function dialog(title,body){say('#dialog-title',title);$('#dialog-body').innerHTML=body;const d=$('#preview-dialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','')}
function closeDialog(){const d=$('#preview-dialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open')}
function saveNote(){clearTimeout(noteTimer);noteTimer=null;return window.CourtApp?.saveNote();}
function exportRecords(){if(window.CourtApp)return window.CourtApp.exportRecords();clearTimeout(draftTimer);clearTimeout(noteTimer);const d=draftData();const payload={...state,draft:hasDraft(d)?d:state.draft,note:$('#activity-text').value,intent,exported:new Date().toISOString(),scope:'Local preview only. File bytes are not included.'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});try{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sidecourt-local-records.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say('#export-status','Export prepared, including current unsaved text. File bytes are not included. Check your browser’s download location.')}catch{dialog('Copy your local records','<p>Download is unavailable. Copy the text below and save it in a file.</p><label class="field">Local records<textarea id="export-copy" rows="10"></textarea></label>');$('#export-copy').value=JSON.stringify(payload,null,2)}}
function exitDemo(){clearTimeout(demoTimer);clearTimeout(holdTimer);holdStart=0;demoActive=false;$('#cleaning-demo').classList.remove('is-active');$('#start-cleaning').hidden=false;$('#hold-return').hidden=true;$('#exit-cleaning').hidden=true;say('#demo-heading','DON’T REACT.');say('#demo-message','I’m just cleaning you.');say('#demo-status','')}
$('#start-cleaning').addEventListener('click',()=>{demoActive=true;$('#cleaning-demo').classList.add('is-active');$('#start-cleaning').hidden=true;$('#hold-return').hidden=false;$('#exit-cleaning').hidden=false;say('#demo-heading','CLEANING PREVIEW');say('#demo-message','Only this panel has changed. Your device input is not blocked.');say('#demo-status','Hold the return button for 3 seconds, choose Exit preview, or press Escape.');$('#hold-return').focus();demoTimer=setTimeout(exitDemo,30000)});
function beginHold(){if(!demoActive||holdStart)return;holdStart=Date.now();say('#demo-status','Keep holding for 3 seconds…');holdTimer=setTimeout(()=>{exitDemo();say('#demo-status','Returned to the preview.');$('#start-cleaning').focus()},3000)}
function cancelHold(){if(!holdStart)return;clearTimeout(holdTimer);holdStart=0;if(demoActive)say('#demo-status','Released early. Hold for 3 seconds, or use Exit preview.')}
$('#hold-return').addEventListener('pointerdown',e=>{if(e.button!==0)return;beginHold()});window.addEventListener('pointerup',cancelHold);window.addEventListener('pointercancel',cancelHold);$('#hold-return').addEventListener('pointerleave',cancelHold);$('#hold-return').addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat)beginHold()}});$('#hold-return').addEventListener('keyup',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();cancelHold()}});$('#hold-return').addEventListener('blur',cancelHold);$('#exit-cleaning').addEventListener('click',()=>{exitDemo();$('#start-cleaning').focus()});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&demoActive){exitDemo();$('#start-cleaning').focus()}});window.addEventListener('blur',()=>{if(demoActive)exitDemo()});$('#demo-disclosure').addEventListener('toggle',()=>{if(!$('#demo-disclosure').open)exitDemo()});
$('#work-form').addEventListener('input',e=>{if(e.target.type==='file')return;syncDraftPreview();say('#form-status','Unsaved changes. Save privately when you are ready.');});$('#save-draft').addEventListener('click',saveDraft);$('#preview-work').addEventListener('click',()=>{renderPreview();location.hash='preview'});$('#work-form').addEventListener('submit',e=>{e.preventDefault();window.CourtApp?.submitWork();});
$('#draft-cover').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const thisRead=++coverRead;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024){say('#cover-status','Choose a PNG, JPG or WebP up to 1 MB. Your previous cover is unchanged.');e.target.value='';return}const reader=new FileReader();reader.onerror=()=>say('#cover-status','This image could not be read. Choose another image; your previous cover is unchanged.');reader.onload=()=>{if(thisRead!==coverRead)return;const candidate=safeCover(reader.result);if(!candidate){say('#cover-status','This image could not be used. Choose another image.');return}draftCover=candidate;syncDraftPreview();say('#cover-status','Cover selected. Check the draft saving status below.');saveDraft()};reader.readAsDataURL(file)});
$('#remove-cover').addEventListener('click',()=>{coverRead++;draftCover='';$('#draft-cover').value='';syncDraftPreview();say('#cover-status','Cover removed from the current draft.');saveDraft()});$('#draft-files').addEventListener('change',e=>{if(window.CourtApp){window.CourtApp.storeFiles([...e.target.files]);return}if(e.target.files.length>30){say('#files-status','Select up to 30 files for this preview. Your previous selection is unchanged.');e.target.value='';return}sessionFiles=[...e.target.files];fileMetadata=sessionFiles.map(f=>({name:f.name,size:f.size}));renderFiles();saveDraft()});
$('#activity-form').addEventListener('submit',e=>{e.preventDefault();window.CourtApp?.postObservation();});$('#activity-text').addEventListener('input',()=>say('#activity-status','Not posted. You can save a private note or post when ready.'));$$('[data-intent]').forEach(b=>b.addEventListener('click',()=>{intent=b.dataset.intent;$$('[data-intent]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)))}));
$$('[data-activity]').forEach(b=>b.addEventListener('click',()=>{$$('[data-activity]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));say('#activity-empty',b.dataset.activity==='log'?'No public author updates yet.':'No public activity yet.')}));
$('#save-work').addEventListener('click',()=>window.CourtApp?.toggleSaved());
$('#share-work').addEventListener('click',()=>window.CourtApp?.shareWork());
$$('[data-board-info]').forEach(b=>b.addEventListener('click',()=>dialog('What the board shows','<p>Public counts are not connected in this preview. A dash means unavailable, not zero. CleanPause is a founder work; no community activity is implied.</p><p>Contributions should represent recorded help, not every comment or suggestion.</p>')));
$('#drop-search').addEventListener('input',()=>filterWorks(null,true));$('#need-filter').addEventListener('change',()=>filterWorks(null,true));$$('[data-discovery]').forEach(b=>b.addEventListener('click',()=>{$$('[data-discovery]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));filterWorks(null,true)}));$('#reset-search').addEventListener('click',()=>{filterWorks(new URLSearchParams());filterWorks(null,true);$('#drop-search').focus()});
$('#save-profile').addEventListener('click',()=>{location.hash='court?tab=account'});$('#export-records').addEventListener('click',()=>window.CourtApp?.exportRecords());
$('#clear-local').addEventListener('click',()=>{location.hash='court?tab=privacy'});
$('#preview-dialog .close').addEventListener('click',closeDialog);$('#preview-dialog').addEventListener('click',e=>{if(e.target===$('#preview-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
if($('#scene-select'))$('#scene-select').innerHTML=Object.entries(names).map(([key,name])=>`<option value="${key}">${name}</option>`).join('');$('#scene-select')?.addEventListener('change',e=>{location.hash=e.target.value;if($('.review'))$('.review').open=false});window.addEventListener('hashchange',route);$('.skip').addEventListener('click',e=>{e.preventDefault();const target=$($('.skip').getAttribute('href'));target.focus();target.scrollIntoView({block:'start'})});
$$('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;const p=img.closest('.square,.showcase-cover');if(p)p.classList.add('no-cover');else if(img.id==='draft-preview-cover'){say('#cover-status','The selected cover could not be displayed. Remove it or choose another image.');$('#draft-cover-placeholder').hidden=false}else if(img.closest('.brand')){const span=document.createElement('span');span.textContent='SideCourt home';span.style.fontSize='16px';img.after(span)}else if(img.classList.contains('work-media')){const fallback=document.createElement('p');fallback.className='local-note';fallback.textContent='Artwork unavailable. The work’s details and links are still available.';img.after(fallback)}}));
function flushPending(){}
window.addEventListener('pagehide',flushPending);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushPending()});
window.addEventListener('beforeunload',e=>{flushPending();const d=draftData();if((hasDraft(d)&&JSON.stringify(d)!==JSON.stringify(state.draft))||$('#activity-text').value!==state.note){e.preventDefault();e.returnValue=''}});
window.SC={get state(){return state},reset(){coverRead++;clearTimeout(draftTimer);clearTimeout(noteTimer);state=blank();draftCover="";fileMetadata=[];sessionFiles=[];restoreDraft();$("#activity-text").value="";},commit,esc,safeURL,sanitizeDraft,str,dialog,closeDialog,saveDraft,saveNote,renderPreview,restoreDraft,renderFiles,syncDraftPreview,draftData,hasDraft,flushPending,route,
activate(draft,workspace){if(!commit({draft,workspace},'#form-status','Draft selected.'))return false;clearTimeout(draftTimer);draftTimer=null;coverRead++;sessionFiles=[];restoreDraft();return true},
setFiles(metadata,files){fileMetadata=metadata;sessionFiles=files;renderFiles()},
safeToSwitch(){const d=draftData();if(hasDraft(d)&&JSON.stringify(d)!==JSON.stringify(state.draft)){if(!saveDraft())return false}return true},
get sessionFiles(){return sessionFiles}};
$('#activity-text').value=state.note;$$('[data-intent]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.intent===intent)));restoreDraft();updateSaved();const dimensions=()=>$('#viewport-size')&&say('#viewport-size',`Viewport: ${window.innerWidth} × ${window.innerHeight}. Resize to review layout.`);window.addEventListener('resize',dimensions);dimensions();route();if(loadWarning)dialog('Local storage unavailable',`<p>${esc(loadWarning)}</p>`);
})();
