/* Shared visual shell. Account services are handled by CourtApp; drafts here stay in memory. */
(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY=document.documentElement.dataset.storageKey==='sidecourt-visitor-v1'?'sidecourt-visitor-v1':'sidecourt-marketing-candidate-v1';
const names={home:'Home',drops:'DROPS',season:'Season I','get-on':'Get on the court',inside:'The Inside',white:'Your draft',work:'Post',account:'Account connections',player:'Profile',court:'Your Court',settings:'Settings',preview:'Private work preview','not-found':'Page not found','season-join':'Prepare your Season entry','season-entry':'Your Season entry'};
const blank=()=>({version:1,saved:false,note:'',intent:'',name:'',draft:null,workspace:{},updated:''});
const str=(v,n=8000)=>typeof v==='string'?v.slice(0,n):'';
const safeURL=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const safeCover=v=>typeof v==='string'&&v.length<1500000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v)?v:'';
const sanitizeDraft=d=>d&&typeof d==='object'?{kind:d.kind==='thought'?'thought':'work',name:str(d.name,48),author:str(d.author,32),description:str(d.description,8000),url:str(d.url,2048),why:str(d.why),start:str(d.start),invitation:['question','need'].includes(d.invitation)?d.invitation:'none',invitationBody:str(d.invitationBody),cardLine:str(d.cardLine,100),repository:str(d.repository,2048),reuse:str(d.reuse,1000),cover:safeCover(d.cover),files:Array.isArray(d.files)?d.files.slice(0,30).map(f=>({name:str(f?.name,200),size:Number.isFinite(f?.size)&&f.size>=0?f.size:0})):[]}:null;
let state=blank(),loadWarning='';
// Cloud mode starts with no prototype records. Draft text stays in memory until explicitly saved.
let draftCover=state.draft?.cover||'',fileMetadata=state.draft?.files||[],sessionFiles=[],coverRead=0;
let draftTimer,noteTimer,intent=state.intent,current='',dropReturn='#drops',insideReturn='#home';
const scrolls=new Map();
const say=(selector,message)=>{$(selector).textContent=message};
function commit(patch,selector,success){
 const next={...state,...patch,updated:new Date().toISOString()};
 try{state=next;if(selector)say(selector,success);return true}
 catch{if(selector)say(selector,'Not saved. This browser could not store the change. Your current text is still here; export it from Settings before closing.');return false}
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const permissionChoices=['View only','Use without modification','Collaborate on specified parts','Collaborate on the whole work','Author-defined terms'];
function restorePermissions(){const text=$('[name=reuse]').value,match=permissionChoices.find(v=>(text==='Participation: '+v||text.startsWith('Participation: '+v+'\n')));$('#collaboration-choice').value=match||'';$('#collaboration-terms').value=match?text.slice(('Participation: '+match+'\n').length):text;}
function updatePermissions(){const mode=$('#collaboration-choice').value,terms=$('#collaboration-terms').value.trim();$('[name=reuse]').value=mode?'Participation: '+mode+'\n'+terms:terms;}
function permissionsReady(){const mode=$('#collaboration-choice').value,terms=$('#collaboration-terms').value.trim();if(!mode||((mode.startsWith('Collaborate')||mode==='Author-defined terms')&&!terms)){say('#permissions-status',!mode?'Choose how people may take part before adding materials or submitting.':'Describe the scope, boundaries and where to collaborate before continuing.');$('#collaboration-choice').focus();return false}say('#permissions-status','Your chosen terms will appear on the published post.');return true;}
function draftData(){const f=new FormData($('#work-form'));return {kind:f.get('kind')==='thought'?'thought':'work',name:str(f.get('name'),48),author:str(f.get('author'),32),description:str(f.get('description'),8000),url:str(f.get('url'),2048),why:str(f.get('why')),start:str(f.get('start')),invitation:f.get('kind')==='thought'?'none':str(f.get('invitationBody')).trim()?'need':'none',invitationBody:str(f.get('invitationBody')),cardLine:str(f.get('cardLine'),100),repository:str(f.get('repository'),2048),reuse:str(f.get('reuse'),1000),cover:draftCover,files:fileMetadata}}
function hasDraft(d){return !!d&&(!!d.name.trim()||!!d.description.trim()||!!d.url.trim()||!!d.why.trim()||!!d.start.trim()||!!d.invitationBody.trim()||!!d.cardLine?.trim()||!!d.repository?.trim()||!!d.reuse?.trim()||!!d.cover||d.files.length>0)}
function saveDraft(){clearTimeout(draftTimer);draftTimer=null;return window.CourtApp?.saveDraft();}
function syncDraftPreview(){const d=draftData();if($('#post-title-label'))$('#post-title-label').textContent=d.kind==='thought'?'What do you need a hand with?':'Name your work';if($('#post-body-label'))$('#post-body-label').textContent=d.kind==='thought'?'What would help?':'What did you make?';if($('#post-body-help'))$('#post-body-help').textContent=d.kind==='thought'?'What are you trying to do, where are you stuck, and what small help would move it forward?':'Tell people what it is and what made you start.';say('#draft-preview-name',d.name||'Your title');say('#draft-preview-author',d.author?`BY ${d.author}`:'Your author name');say('#draft-preview-description',d.description||'One sentence about what someone can explore.');$('#draft-preview-cover').hidden=!draftCover;$('#draft-cover-placeholder').hidden=!!draftCover;if(draftCover)$('#draft-preview-cover').src=draftCover;else $('#draft-preview-cover').removeAttribute('src');$('#remove-cover').hidden=!draftCover;$('#help-options').hidden=d.kind==='thought';$('#post-why-label').textContent=d.kind==='thought'?'A little context':'Why it exists';$('#post-start-label').textContent=d.kind==='thought'?'Useful details for someone helping':'Use & compatibility';const attachments=$('#submission-attachments');if(attachments.dataset.kind!==d.kind){attachments.open=d.kind!=='thought';attachments.dataset.kind=d.kind;}$('#submission-material-help').textContent=d.kind==='thought'?'Words are enough. Links, images and files are optional.':'Add at least one link, image or file before submitting.';$('#work-description').placeholder=d.kind==='thought'?'Describe the situation and a specific next step someone could help with.':'Tell us what you made and what you’d like to share.';$$('[data-count]').forEach(n=>{const f=document.getElementById(n.dataset.count);n.textContent=`${f.value.length} / ${f.maxLength}`});window.CourtApp?.renderLiveCard(d)}
function restoreDraft(){const f=$('#work-form');f.reset();const d=state.draft;if(d){for(const [key,value] of Object.entries(d)){const input=f.elements.namedItem(key);if(!input||['cover','files'].includes(key))continue;if(key==='invitation')input.value=value;else input.value=value;}}else $('#draft-author').value=state.name;draftCover=d?.cover||'';fileMetadata=d?.files||[];restorePermissions();syncDraftPreview();renderFiles()}
function renderFiles(){say('#files-status',fileMetadata.length?`${fileMetadata.map(f=>f.name).join(', ')}. Check upload status below; public downloads need review and your publishing choice.`:'Optional individually · up to 50 MB per file. Files stay private until you publish them.')}
function renderPreview(d=draftData()){if(window.CourtApp?.renderPostPreview){window.CourtApp.renderPostPreview(d);return}const url=safeURL(d.url);if(!hasDraft(d)){$('#full-work-preview').innerHTML='<div class="empty glass"><h2>A place for your first draft.</h2><p>Start with a name or a sentence. You can preview before filling everything in.</p><a class="button" href="#white">Start a draft →</a></div>';return}
 $('#full-work-preview').innerHTML=`<section class="work-heading"><div><p class="attribution">${esc(d.author?'BY '+d.author:'AUTHOR NAME NOT ADDED')}</p><h1>${esc(d.name||'Untitled work')}</h1><p class="preserve-text">${esc(d.description||'Add your description.')}</p>${url?`<a class="button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Explore this work ↗</a>`:d.url?'<p class="local-note">This link is not a valid http or https address. Edit it before sharing.</p>':''}</div>${d.cover?`<img class="work-media" src="${esc(d.cover)}" alt="Your selected cover">`:'<div class="cover-placeholder">Your work. Your point of view.</div>'}</section><div class="glass preview-details">${d.why?`<h2>Why I made it.</h2><p>${esc(d.why)}</p>`:''}${d.start?`<h2>Where to start.</h2><p>${esc(d.start)}</p>`:''}${d.invitation!=='none'?`<h2>${d.invitation==='need'?'An invitation to help.':'A question from the author.'}</h2><p>${esc(d.invitationBody||'Add the question or invitation you would like someone to see.')}</p>`:''}${d.files.length?`<h2>Files</h2><p>Names and sizes only. Files have not been uploaded or published.</p><ul class="preview-file-list">${d.files.map(f=>`<li>${esc(f.name)} · ${Math.ceil(f.size/1024)} KB${sessionFiles.some(s=>s.name===f.name&&s.size===f.size)?' · selected this session':' · select again in the editor'}</li>`).join('')}</ul>`:''}<p class="local-note">Private layout preview. Nothing on this page has been published or sent for review.</p></div>`;
}
function renderCourt(){if(window.CourtApp)return window.CourtApp.renderCourt();$('#court-content').innerHTML='<h2>Your workspace is loading.</h2><p>If this message stays here, reload the page. Your account has not changed.</p><a class="text-link" href="#drops">Explore works →</a>';}

function filterWorks(params,write=false){if(window.CourtApp)return window.CourtApp.filterWorks(params,write);$('#drop-results').innerHTML='';say('#discovery-context','Loading published posts…');}

function route(force=false){const hash=location.hash||'#home';if(hash===current&&force!==true)return;if(hash.startsWith('#main-'))return;const [raw,query='']=hash.slice(1).split('?'),page=Object.hasOwn(names,raw)?raw:'not-found',previous=current.split('?')[0];if(current)scrolls.set(current,window.scrollY);if(previous==='#drops')dropReturn=current;if(page==='inside'&&previous&&previous!=='#inside')insideReturn=current;current=hash;
 $$('[data-page]').forEach(n=>n.hidden=n.dataset.page!==page);delete document.documentElement.dataset.entry;$$('.mobile-nav[open]').forEach(n=>n.open=false);$$('.nav a,.mobile-nav a').forEach(n=>{const hit=n.getAttribute('href')==='#'+page;if(hit)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current')});if($('#scene-select'))$('#scene-select').value=page;$('.skip').setAttribute('href','#main-'+page);document.title='SideCourt · '+names[page];
 if(page==='drops')filterWorks(new URLSearchParams(query));if(page==='court')renderCourt();if(page==='preview')renderPreview();window.CourtApp?.onRoute(page,new URLSearchParams(query));
 $$('[data-back-drops]').forEach(a=>a.setAttribute('href',dropReturn));$$('[data-return]').forEach(a=>a.setAttribute('href',insideReturn));
 const main=$('#main-'+page);main.focus({preventScroll:true});requestAnimationFrame(()=>{if(current!==hash)return;const p=new URLSearchParams(query);if(page==='season'&&p.get('section')==='rules'){const target=$('#season-rules');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else if(page==='preview'&&p.get('section')==='details'&&$('#preview-details')){const target=$('#preview-details');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else if(page==='work'&&(p.has('question')||p.has('compose'))){const target=p.has('question')?($('#author-question')||$('#around-work')):$('#activity-text');if(p.has('question'))target.setAttribute('tabindex','-1');target.scrollIntoView({block:'start',behavior:'auto'});target.focus({preventScroll:true})}else window.scrollTo({top:scrolls.get(hash)||0,behavior:'auto'})});
}
function dialog(title,body){say('#dialog-title',title);$('#dialog-body').innerHTML=body;const d=$('#preview-dialog');d.classList.toggle('court-dialog',!!document.querySelector('.scene:not([hidden]) :is(#main-court,#main-white,#main-preview,#main-account,.court-public-post,.court-profile-page)'));if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','')}
function closeDialog(){const d=$('#preview-dialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open')}
function saveNote(){clearTimeout(noteTimer);noteTimer=null;return window.CourtApp?.saveNote();}
function exportRecords(){if(window.CourtApp)return window.CourtApp.exportRecords();clearTimeout(draftTimer);clearTimeout(noteTimer);const d=draftData();const payload={...state,draft:hasDraft(d)?d:state.draft,note:($('#activity-text')?.value||''),intent,exported:new Date().toISOString(),scope:'Local preview only. File bytes are not included.'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});try{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sidecourt-local-records.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say('#export-status','Export prepared, including current unsaved text. File bytes are not included. Check your browser’s download location.')}catch{dialog('Copy your local records','<p>Download is unavailable. Copy the text below and save it in a file.</p><label class="field">Local records<textarea id="export-copy" rows="10"></textarea></label>');$('#export-copy').value=JSON.stringify(payload,null,2)}}
$('#work-form').addEventListener('input',e=>{if(e.target.type==='file')return;if(['collaboration-choice','collaboration-terms'].includes(e.target.id))updatePermissions();syncDraftPreview();say('#form-status','Unsaved changes. Save privately when you are ready.');});$('#save-draft').addEventListener('click',saveDraft);$('#preview-work').addEventListener('click',()=>{renderPreview();location.hash='preview'});$('#work-form').addEventListener('submit',e=>{e.preventDefault();window.CourtApp?.submitWork();});
function chooseCover(file){if(!file)return;if(!permissionsReady())return;const thisRead=++coverRead;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024){say('#cover-status','Choose a PNG, JPG or WebP up to 1 MB. Your previous cover is unchanged.');$('#draft-cover').value='';return}const reader=new FileReader();reader.onerror=()=>say('#cover-status','This image could not be read. Choose another image; your previous cover is unchanged.');reader.onload=()=>{if(thisRead!==coverRead)return;const candidate=safeCover(reader.result);if(!candidate){say('#cover-status','This image could not be used. Choose another image.');return}draftCover=candidate;syncDraftPreview();const zone=$('#image-dropzone');zone.classList.remove('image-received');void zone.offsetWidth;zone.classList.add('image-received');say('#cover-status','Cover selected. Check the draft saving status below.');saveDraft()};reader.readAsDataURL(file)}
$('#draft-cover').addEventListener('change',e=>chooseCover(e.target.files?.[0]));
const imageZone=$('#image-dropzone');let dragDepth=0;imageZone.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;imageZone.classList.add('is-dragging')});imageZone.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy'});imageZone.addEventListener('dragleave',()=>{if(--dragDepth<=0){dragDepth=0;imageZone.classList.remove('is-dragging')}});imageZone.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;imageZone.classList.remove('is-dragging');const files=[...(e.dataTransfer?.files||[])];if(files.length!==1){say('#cover-status','Choose one image for the cover. Your previous cover is unchanged.');return}chooseCover(files[0])});imageZone.addEventListener('animationend',()=>imageZone.classList.remove('image-received'));

$('#remove-cover').addEventListener('click',()=>{coverRead++;draftCover='';$('#draft-cover').value='';syncDraftPreview();say('#cover-status','Cover removed from the current draft.');saveDraft()});$('#draft-files').addEventListener('change',e=>{if(window.CourtApp){window.CourtApp.storeFiles([...e.target.files]);return}if(e.target.files.length>30){say('#files-status','Select up to 30 files for this preview. Your previous selection is unchanged.');e.target.value='';return}sessionFiles=[...e.target.files];fileMetadata=sessionFiles.map(f=>({name:f.name,size:f.size}));renderFiles();saveDraft()});
$$('[data-board-info]').forEach(b=>b.addEventListener('click',()=>dialog('What the board shows','<p>A dash means the count is unavailable. Public totals include published works and confirmed contributions.</p><p>Contributions should represent recorded help, not every comment or suggestion.</p>')));
$('#drop-search').addEventListener('input',()=>filterWorks(null,true));$('#need-filter').addEventListener('change',()=>filterWorks(null,true));$$('[data-discovery]').forEach(b=>b.addEventListener('click',()=>{$$('[data-discovery]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));filterWorks(null,true)}));$('#reset-search').addEventListener('click',()=>{filterWorks(new URLSearchParams());filterWorks(null,true);$('#drop-search').focus()});
$('#preview-dialog .close').addEventListener('click',closeDialog);$('#preview-dialog').addEventListener('click',e=>{if(e.target===$('#preview-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
if($('#scene-select'))$('#scene-select').innerHTML=Object.entries(names).map(([key,name])=>`<option value="${key}">${name}</option>`).join('');$('#scene-select')?.addEventListener('change',e=>{location.hash=e.target.value;if($('.review'))$('.review').open=false});window.addEventListener('hashchange',route);$('.skip').addEventListener('click',e=>{e.preventDefault();const target=$($('.skip').getAttribute('href'));target.focus();target.scrollIntoView({block:'start'})});
$$('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;const p=img.closest('.square,.showcase-cover');if(p)p.classList.add('no-cover');else if(img.id==='draft-preview-cover'){say('#cover-status','The selected cover could not be displayed. Remove it or choose another image.');$('#draft-cover-placeholder').hidden=false}else if(img.closest('.brand')){const span=document.createElement('span');span.textContent='SideCourt home';span.style.fontSize='16px';img.after(span)}else if(img.classList.contains('work-media')){const fallback=document.createElement('p');fallback.className='local-note';fallback.textContent='Artwork unavailable. The work’s details and links are still available.';img.after(fallback)}}));
function flushPending(){return window.CourtApp?.retainDraft?.()}
window.addEventListener('pagehide',flushPending);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushPending()});
window.addEventListener('beforeunload',e=>{flushPending();const d=draftData(),draftKept=window.CourtApp?.retainDraft?.();if((!draftKept&&hasDraft(d)&&JSON.stringify(d)!==JSON.stringify(state.draft))||($('#activity-text')?.value||'')!==state.note){e.preventDefault();e.returnValue=''}});
window.SC={get state(){return state},reset(){coverRead++;clearTimeout(draftTimer);clearTimeout(noteTimer);state=blank();draftCover="";fileMetadata=[];sessionFiles=[];restoreDraft();},commit,esc,safeURL,sanitizeDraft,str,dialog,closeDialog,saveDraft,saveNote,renderPreview,restoreDraft,renderFiles,syncDraftPreview,draftData,hasDraft,flushPending,route,
activate(draft,workspace){if(!commit({draft,workspace},'#form-status','Draft selected.'))return false;clearTimeout(draftTimer);draftTimer=null;coverRead++;sessionFiles=[];restoreDraft();return true},
setFiles(metadata,files){fileMetadata=metadata;sessionFiles=files;renderFiles()},
safeToSwitch(){const d=draftData();if(hasDraft(d)&&JSON.stringify(d)!==JSON.stringify(state.draft)){if(!saveDraft())return false}return true},
permissionsReady,get sessionFiles(){return sessionFiles}};
$$('[data-intent]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.intent===intent)));restoreDraft();const dimensions=()=>$('#viewport-size')&&say('#viewport-size',`Viewport: ${window.innerWidth} × ${window.innerHeight}. Resize to review layout.`);window.addEventListener('resize',dimensions);dimensions();route();if(loadWarning)dialog('Local storage unavailable',`<p>${esc(loadWarning)}</p>`);
})();
