// Generated by scripts/build_sw.py. No API, analytics or parent-site caching.
const BASE = new URL('./', self.location.href);
const PREFIX = 'daycup-shell:' + BASE.pathname + ':';
const CACHE = PREFIX + '8b6e144556c7c0dc';
const ASSETS = ["index.html", "app.js", "i18n.js", "rules.js", "catalog-extension.js", "brew-knowledge.js", "equipment.js", "bean-options.js", "curation.js", "equipment-directory.json", "bean-options.json", "style.css", "manifest.json", "icon.svg", "icon-180.png", "icon-192.png", "icon-512.png", "icon-maskable-512.png", "privacy.html"];
const URLS = ASSETS.map(name => new URL(name, BASE).href);
self.addEventListener('install', event => {
 event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(URLS)));
 // Do not skipWaiting: avoid replacing an open brew session during an update.
});
self.addEventListener('activate', event => {
 event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
 const request = event.request, url = new URL(request.url);
 if(request.method !== 'GET' || url.origin !== BASE.origin || !url.pathname.startsWith(BASE.pathname)) return;
 const relative = url.pathname.slice(BASE.pathname.length);
 // Navigation only to our entry document, not arbitrary parent/API paths.
 const entry = relative === '' || relative === 'index.html';
 if(!entry && !ASSETS.includes(relative)) return;
 const key = new URL(entry ? 'index.html' : relative, BASE).href;
 event.respondWith(caches.open(CACHE).then(async cache => {
  const cached = await cache.match(key);
  if(cached) return cached;
  return fetch(request); // Never store unknown/dynamic responses.
 }));
});
